//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.0.0 (NJsonSchema v11.5.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { Inject, Injectable, InjectionToken, Optional } from '@angular/core';
import { Observable, of as _observableOf, throwError as _observableThrow } from 'rxjs';
import { catchError as _observableCatch, mergeMap as _observableMergeMap } from 'rxjs/operators';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class ApiClient {
  private http: HttpClient;
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

  constructor(
    @Inject(HttpClient) http: HttpClient,
    @Optional() @Inject(API_BASE_URL) baseUrl?: string
  ) {
    this.http = http;
    this.baseUrl = baseUrl ?? 'http://localhost:7245';
  }

  /**
   * Get User Info by User ID
   * @param userId Id of an existing user.
   * @return User Found
   */
  getUsersUserId(userId: number): Observable<User> {
    let url_ = this.baseUrl + '/users/{userId}';
    if (userId === undefined || userId === null)
      throw new globalThis.Error("The parameter 'userId' must be defined.");
    url_ = url_.replace('{userId}', encodeURIComponent('' + userId));
    url_ = url_.replace(/[?&]$/, '');

    let options_: any = {
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({
        Accept: 'application/json',
      }),
    };

    return this.http
      .request('get', url_, options_)
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processGetUsersUserId(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processGetUsersUserId(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<User>;
            }
          } else return _observableThrow(response_) as any as Observable<User>;
        })
      );
  }

  protected processGetUsersUserId(response: HttpResponseBase): Observable<User> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          let result200: any = null;
          let resultData200 =
            _responseText === '' ? null : JSON.parse(_responseText, this.jsonParseReviver);
          result200 = User.fromJS(resultData200);
          return _observableOf(result200);
        })
      );
    } else if (status === 404) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException('User Not Found', status, _responseText, _headers);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException(
            'An unexpected server error occurred.',
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf<User>(null as any);
  }

  /**
   * Update User Information
   * @param body (optional)
   * @param userId Id of an existing user.
   * @return User Updated
   */
  patchUsersUserId(body: Body | undefined, userId: number): Observable<User> {
    let url_ = this.baseUrl + '/users/{userId}';
    if (userId === undefined || userId === null)
      throw new globalThis.Error("The parameter 'userId' must be defined.");
    url_ = url_.replace('{userId}', encodeURIComponent('' + userId));
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: any = {
      body: content_,
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({
        'Content-Type': 'application/json',
        Accept: 'application/json',
      }),
    };

    return this.http
      .request('patch', url_, options_)
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processPatchUsersUserId(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processPatchUsersUserId(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<User>;
            }
          } else return _observableThrow(response_) as any as Observable<User>;
        })
      );
  }

  protected processPatchUsersUserId(response: HttpResponseBase): Observable<User> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          let result200: any = null;
          let resultData200 =
            _responseText === '' ? null : JSON.parse(_responseText, this.jsonParseReviver);
          result200 = User.fromJS(resultData200);
          return _observableOf(result200);
        })
      );
    } else if (status === 404) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException('User Not Found', status, _responseText, _headers);
        })
      );
    } else if (status === 409) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException('Email Already Taken', status, _responseText, _headers);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException(
            'An unexpected server error occurred.',
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf<User>(null as any);
  }

  /**
   * Create New User
   * @param body (optional)
   * @return User Created
   */
  postUser(body: Body2 | undefined): Observable<User> {
    let url_ = this.baseUrl + '/users';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: any = {
      body: content_,
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({
        'Content-Type': 'application/json',
        Accept: 'application/json',
      }),
    };

    return this.http
      .request('post', url_, options_)
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processPostUser(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processPostUser(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<User>;
            }
          } else return _observableThrow(response_) as any as Observable<User>;
        })
      );
  }

  protected processPostUser(response: HttpResponseBase): Observable<User> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          let result200: any = null;
          let resultData200 =
            _responseText === '' ? null : JSON.parse(_responseText, this.jsonParseReviver);
          result200 = User.fromJS(resultData200);
          return _observableOf(result200);
        })
      );
    } else if (status === 400) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException('Missing Required Information', status, _responseText, _headers);
        })
      );
    } else if (status === 409) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException('Email Already Taken', status, _responseText, _headers);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException(
            'An unexpected server error occurred.',
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf<User>(null as any);
  }

  /**
   * Get All Users
   * @return List of Users
   */
  getUsers(): Observable<User[]> {
    let url_ = this.baseUrl + '/users';
    url_ = url_.replace(/[?&]$/, '');

    let options_: any = {
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({
        Accept: 'application/json',
      }),
    };

    return this.http
      .request('get', url_, options_)
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processGetUsers(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processGetUsers(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<User[]>;
            }
          } else return _observableThrow(response_) as any as Observable<User[]>;
        })
      );
  }

  protected processGetUsers(response: HttpResponseBase): Observable<User[]> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          let result200: any = null;
          let resultData200 =
            _responseText === '' ? null : JSON.parse(_responseText, this.jsonParseReviver);
          if (Array.isArray(resultData200)) {
            result200 = [] as any;
            for (let item of resultData200) result200!.push(User.fromJS(item));
          } else {
            result200 = null as any;
          }
          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException(
            'An unexpected server error occurred.',
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf<User[]>(null as any);
  }

  /**
   * Get All Cars
   * @return List of Cars
   */
  getCars(): Observable<CarDto[]> {
    let url_ = this.baseUrl + '/cars';
    url_ = url_.replace(/[?&]$/, '');

    let options_: any = {
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({
        Accept: 'application/json',
      }),
    };

    return this.http
      .request('get', url_, options_)
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processGetCars(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processGetCars(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<CarDto[]>;
            }
          } else return _observableThrow(response_) as any as Observable<CarDto[]>;
        })
      );
  }

  protected processGetCars(response: HttpResponseBase): Observable<CarDto[]> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          let result200: any = null;
          let resultData200 =
            _responseText === '' ? null : JSON.parse(_responseText, this.jsonParseReviver);
          if (Array.isArray(resultData200)) {
            result200 = [] as any;
            for (let item of resultData200) result200!.push(CarDto.fromJS(item));
          } else {
            result200 = null as any;
          }
          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException(
            'An unexpected server error occurred.',
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf<CarDto[]>(null as any);
  }

  /**
   * Get All Car Parts
   * @return List of Car Parts
   */
  getParts(): Observable<CarPartDto[]> {
    let url_ = this.baseUrl + '/parts';
    url_ = url_.replace(/[?&]$/, '');

    let options_: any = {
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({
        Accept: 'application/json',
      }),
    };

    return this.http
      .request('get', url_, options_)
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processGetParts(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processGetParts(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<CarPartDto[]>;
            }
          } else return _observableThrow(response_) as any as Observable<CarPartDto[]>;
        })
      );
  }

  protected processGetParts(response: HttpResponseBase): Observable<CarPartDto[]> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          let result200: any = null;
          let resultData200 =
            _responseText === '' ? null : JSON.parse(_responseText, this.jsonParseReviver);
          if (Array.isArray(resultData200)) {
            result200 = [] as any;
            for (let item of resultData200) result200!.push(CarPartDto.fromJS(item));
          } else {
            result200 = null as any;
          }
          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException(
            'An unexpected server error occurred.',
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf<CarPartDto[]>(null as any);
  }

  /**
   * User Login
   * @return Login Successful
   */
  postLogin(body: AuthRequest): Observable<LoginResponse> {
    let url_ = this.baseUrl + '/login';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: any = {
      body: content_,
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({
        'Content-Type': 'application/json',
        Accept: 'application/json',
      }),
    };

    return this.http
      .request('post', url_, options_)
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processPostLogin(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processPostLogin(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<LoginResponse>;
            }
          } else return _observableThrow(response_) as any as Observable<LoginResponse>;
        })
      );
  }

  protected processPostLogin(response: HttpResponseBase): Observable<LoginResponse> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          let result200: any = null;
          let resultData200 =
            _responseText === '' ? null : JSON.parse(_responseText, this.jsonParseReviver);
          result200 = LoginResponse.fromJS(resultData200);
          return _observableOf(result200);
        })
      );
    } else if (status === 400) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException('Missing Credentials', status, _responseText, _headers);
        })
      );
    } else if (status === 401) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException('Invalid Email or Password', status, _responseText, _headers);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText) => {
          return throwException(
            'An unexpected server error occurred.',
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf<LoginResponse>(null as any);
  }
}

export class User implements IUser {
  id?: number;
  email?: string;
  createDate?: Date;
  identityUserId?: string;
  role?: number;
  name?: string;

  [key: string]: any;

  constructor(data?: IUser) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.id = _data['id'];
      this.email = _data['email'];
      this.createDate = _data['createDate']
        ? new Date(_data['createDate'].toString())
        : (undefined as any);
      this.identityUserId = _data['identityUserId'];
      this.role = _data['role'];
      this.name = _data['name'];
    }
  }

  static fromJS(data: any): User {
    data = typeof data === 'object' ? data : {};
    let result = new User();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['id'] = this.id;
    data['email'] = this.email;
    data['createDate'] = this.createDate ? formatDate(this.createDate) : (undefined as any);
    data['identityUserId'] = this.identityUserId;
    data['role'] = this.role;
    data['name'] = this.name;
    return data;
  }
}

export interface IUser {
  id?: number;
  email?: string;
  createDate?: Date;
  identityUserId?: string;
  role?: number;
  name?: string;

  [key: string]: any;
}

export class Car implements ICar {
  id?: number;
  supplierId?: number;
  purchaseDate?: Date;
  brand?: string;
  model?: string;
  manufactureYear?: number;
  vehicleRegistrationCertificate?: string;
  purchasePrice?: number;

  [key: string]: any;

  constructor(data?: ICar) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.id = _data['id'];
      this.supplierId = _data['supplierId'];
      this.purchaseDate = _data['purchaseDate']
        ? new Date(_data['purchaseDate'].toString())
        : (undefined as any);
      this.brand = _data['brand'];
      this.model = _data['model'];
      this.manufactureYear = _data['manufactureYear'];
      this.vehicleRegistrationCertificate = _data['vehicleRegistrationCertificate'];
      this.purchasePrice = _data['purchasePrice'];
    }
  }

  static fromJS(data: any): Car {
    data = typeof data === 'object' ? data : {};
    let result = new Car();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['id'] = this.id;
    data['supplierId'] = this.supplierId;
    data['purchaseDate'] = this.purchaseDate ? this.purchaseDate.toISOString() : (undefined as any);
    data['brand'] = this.brand;
    data['model'] = this.model;
    data['manufactureYear'] = this.manufactureYear;
    data['vehicleRegistrationCertificate'] = this.vehicleRegistrationCertificate;
    data['purchasePrice'] = this.purchasePrice;
    return data;
  }
}

export interface ICar {
  id?: number;
  supplierId?: number;
  purchaseDate?: Date;
  brand?: string;
  model?: string;
  manufactureYear?: number;
  vehicleRegistrationCertificate?: string;
  purchasePrice?: number;

  [key: string]: any;
}

export class Client implements IClient {
  clientId?: number;
  name?: string;
  phone?: string;

  [key: string]: any;

  constructor(data?: IClient) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.clientId = _data['clientId'];
      this.name = _data['name'];
      this.phone = _data['phone'];
    }
  }

  static fromJS(data: any): Client {
    data = typeof data === 'object' ? data : {};
    let result = new Client();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['clientId'] = this.clientId;
    data['name'] = this.name;
    data['phone'] = this.phone;
    return data;
  }
}

export interface IClient {
  clientId?: number;
  name?: string;
  phone?: string;

  [key: string]: any;
}

export class CarPart implements ICarPart {
  id?: number;
  carId?: number;
  purchaseDate?: Date;
  price?: number;
  name?: string;
  status?: number;
  clientId?: number;

  [key: string]: any;

  constructor(data?: ICarPart) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.id = _data['id'];
      this.carId = _data['carId'];
      this.purchaseDate = _data['purchaseDate']
        ? new Date(_data['purchaseDate'].toString())
        : (undefined as any);
      this.price = _data['price'];
      this.name = _data['name'];
      this.status = _data['status'];
      this.clientId = _data['clientId'];
    }
  }

  static fromJS(data: any): CarPart {
    data = typeof data === 'object' ? data : {};
    let result = new CarPart();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['id'] = this.id;
    data['carId'] = this.carId;
    data['purchaseDate'] = this.purchaseDate ? this.purchaseDate.toISOString() : (undefined as any);
    data['price'] = this.price;
    data['name'] = this.name;
    data['status'] = this.status;
    data['clientId'] = this.clientId;
    return data;
  }
}

export interface ICarPart {
  id?: number;
  carId?: number;
  purchaseDate?: Date;
  price?: number;
  name?: string;
  status?: number;
  clientId?: number;

  [key: string]: any;
}

export class CarImage implements ICarImage {
  id?: number;
  carId?: number;
  image?: string;

  [key: string]: any;

  constructor(data?: ICarImage) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.id = _data['id'];
      this.carId = _data['carId'];
      this.image = _data['image'];
    }
  }

  static fromJS(data: any): CarImage {
    data = typeof data === 'object' ? data : {};
    let result = new CarImage();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['id'] = this.id;
    data['carId'] = this.carId;
    data['image'] = this.image;
    return data;
  }
}

export interface ICarImage {
  id?: number;
  carId?: number;
  image?: string;

  [key: string]: any;
}

export class CarPartImage implements ICarPartImage {
  id?: number;
  carPartId?: number;
  image?: string;

  [key: string]: any;

  constructor(data?: ICarPartImage) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.id = _data['id'];
      this.carPartId = _data['carPartId'];
      this.image = _data['image'];
    }
  }

  static fromJS(data: any): CarPartImage {
    data = typeof data === 'object' ? data : {};
    let result = new CarPartImage();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['id'] = this.id;
    data['carPartId'] = this.carPartId;
    data['image'] = this.image;
    return data;
  }
}

export interface ICarPartImage {
  id?: number;
  carPartId?: number;
  image?: string;

  [key: string]: any;
}

export class Supplier implements ISupplier {
  id?: string;
  name?: string;
  ssn?: string;
  phoneNumber?: string;

  [key: string]: any;

  constructor(data?: ISupplier) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.id = _data['id'];
      this.name = _data['name'];
      this.ssn = _data['ssn'];
      this.phoneNumber = _data['phoneNumber'];
    }
  }

  static fromJS(data: any): Supplier {
    data = typeof data === 'object' ? data : {};
    let result = new Supplier();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['id'] = this.id;
    data['name'] = this.name;
    data['ssn'] = this.ssn;
    data['phoneNumber'] = this.phoneNumber;
    return data;
  }
}

export interface ISupplier {
  id?: string;
  name?: string;
  ssn?: string;
  phoneNumber?: string;

  [key: string]: any;
}

export class CarDto implements ICarDto {
  car?: Car;
  images?: string[];

  [key: string]: any;

  constructor(data?: ICarDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.car = _data['car'] ? Car.fromJS(_data['car']) : (undefined as any);
      if (Array.isArray(_data['images'])) {
        this.images = [] as any;
        for (let item of _data['images']) this.images!.push(item);
      }
    }
  }

  static fromJS(data: any): CarDto {
    data = typeof data === 'object' ? data : {};
    let result = new CarDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['car'] = this.car ? this.car.toJSON() : (undefined as any);
    if (Array.isArray(this.images)) {
      data['images'] = [];
      for (let item of this.images) data['images'].push(item);
    }
    return data;
  }
}

export interface ICarDto {
  car?: Car;
  images?: string[];

  [key: string]: any;
}

export class CarPartDto implements ICarPartDto {
  carPart?: CarPart;
  images?: string[];

  [key: string]: any;

  constructor(data?: ICarPartDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.carPart = _data['carPart'] ? CarPart.fromJS(_data['carPart']) : (undefined as any);
      if (Array.isArray(_data['images'])) {
        this.images = [] as any;
        for (let item of _data['images']) this.images!.push(item);
      }
    }
  }

  static fromJS(data: any): CarPartDto {
    data = typeof data === 'object' ? data : {};
    let result = new CarPartDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['carPart'] = this.carPart ? this.carPart.toJSON() : (undefined as any);
    if (Array.isArray(this.images)) {
      data['images'] = [];
      for (let item of this.images) data['images'].push(item);
    }
    return data;
  }
}

export interface ICarPartDto {
  carPart?: CarPart;
  images?: string[];

  [key: string]: any;
}

export class LoginResponse implements ILoginResponse {
  /** JWT or session token */
  token!: string;
  /** Token expiration timestamp */
  expiresAt!: Date;
  user!: User;

  [key: string]: any;

  constructor(data?: ILoginResponse) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
    if (!data) {
      this.user = new User();
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.token = _data['token'];
      this.expiresAt = _data['expiresAt']
        ? new Date(_data['expiresAt'].toString())
        : (undefined as any);
      this.user = _data['user'] ? User.fromJS(_data['user']) : new User();
    }
  }

  static fromJS(data: any): LoginResponse {
    data = typeof data === 'object' ? data : {};
    let result = new LoginResponse();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['token'] = this.token;
    data['expiresAt'] = this.expiresAt ? this.expiresAt.toISOString() : (undefined as any);
    data['user'] = this.user ? this.user.toJSON() : (undefined as any);
    return data;
  }
}

export interface ILoginResponse {
  /** JWT or session token */
  token: string;
  /** Token expiration timestamp */
  expiresAt: Date;
  user: User;

  [key: string]: any;
}

export class AuthRequest implements IAuthRequest {
  email?: string;
  password?: string;

  [key: string]: any;

  constructor(data?: IAuthRequest) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.email = _data['email'];
      this.password = _data['password'];
    }
  }

  static fromJS(data: any): AuthRequest {
    data = typeof data === 'object' ? data : {};
    let result = new AuthRequest();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['email'] = this.email;
    data['password'] = this.password;
    return data;
  }
}

export interface IAuthRequest {
  email?: string;
  password?: string;

  [key: string]: any;
}

export class Body implements IBody {
  firstName?: string;
  lastName?: string;
  /** If a new email is given, the user's email verified property will be set to false. */
  email?: string;
  dateOfBirth?: string;

  [key: string]: any;

  constructor(data?: IBody) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.firstName = _data['firstName'];
      this.lastName = _data['lastName'];
      this.email = _data['email'];
      this.dateOfBirth = _data['dateOfBirth'];
    }
  }

  static fromJS(data: any): Body {
    data = typeof data === 'object' ? data : {};
    let result = new Body();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['firstName'] = this.firstName;
    data['lastName'] = this.lastName;
    data['email'] = this.email;
    data['dateOfBirth'] = this.dateOfBirth;
    return data;
  }
}

export interface IBody {
  firstName?: string;
  lastName?: string;
  /** If a new email is given, the user's email verified property will be set to false. */
  email?: string;
  dateOfBirth?: string;

  [key: string]: any;
}

export class Body2 implements IBody2 {
  firstName!: string;
  lastName!: string;
  email!: string;
  dateOfBirth!: Date;

  [key: string]: any;

  constructor(data?: IBody2) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.firstName = _data['firstName'];
      this.lastName = _data['lastName'];
      this.email = _data['email'];
      this.dateOfBirth = _data['dateOfBirth']
        ? new Date(_data['dateOfBirth'].toString())
        : (undefined as any);
    }
  }

  static fromJS(data: any): Body2 {
    data = typeof data === 'object' ? data : {};
    let result = new Body2();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['firstName'] = this.firstName;
    data['lastName'] = this.lastName;
    data['email'] = this.email;
    data['dateOfBirth'] = this.dateOfBirth ? formatDate(this.dateOfBirth) : (undefined as any);
    return data;
  }
}

export interface IBody2 {
  firstName: string;
  lastName: string;
  email: string;
  dateOfBirth: Date;

  [key: string]: any;
}

function formatDate(d: Date) {
  return (
    d.getFullYear() +
    '-' +
    (d.getMonth() < 9 ? '0' + (d.getMonth() + 1) : d.getMonth() + 1) +
    '-' +
    (d.getDate() < 10 ? '0' + d.getDate() : d.getDate())
  );
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any
): Observable<any> {
  if (result !== null && result !== undefined) return _observableThrow(result);
  else return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
  return new Observable<string>((observer: any) => {
    if (!blob) {
      observer.next('');
      observer.complete();
    } else {
      let reader = new FileReader();
      reader.onload = (event) => {
        observer.next((event.target as any).result);
        observer.complete();
      };
      reader.readAsText(blob);
    }
  });
}
